### PR TITLE
Suggest putting the apt source in its own file

### PR DESCRIPTION
**Pull request by SuperSandro2000**
So it is a bit cleaner and the main file is not that cluttered.

### CODE REVIEW

**Comment by knqyf263** [comment]
Thanks!!

**Comment by knqyf263** [comment]
@SuperSandro2000 Thank you for contributing to Trivy. I have not prepared the Contribution License Agreement (CLA), but finally prepared it.

I would like you to sign CLA if possible. I apologize the inconvenience I have caused.
https://portal.helloworks.com/link/wvhTF78a4A9hICrm

If you have any questions, please let me know. Thanks again for your kind cooperation.

**Comment by SuperSandro2000** [comment]
Should be done now

**Comment by knqyf263** [comment]
@SuperSandro2000 Thank you very much!

**Pull request merged**
