### PR TITLE
fix: backport test

### PR DESCRIPTION
**Pull request by knqyf263**

### CODE REVIEW

**Comment by knqyf263** [comment]
@aqua-bot backport release/v0.53

**Comment by knqyf263** [comment]
@aqua-bot backport release/v0.53

**Comment by knqyf263** [comment]
Backport PR created: https://github.com/knqyf263/trivy/pull/65

**Comment by knqyf263** [comment]
@DmitriyLewen Can you try to trigger backport? I want to make sure only maintainers can trigger it. Since you're not a maintainer of my fork, you should not be able to trigger it.

**Comment by DmitriyLewen** [comment]
@aqua-bot backport release/v0.53

**Pull request merged**
