### PR TITLE
Add code snippet reminder on how to print distribution codename

### PR DESCRIPTION
**Pull request by akerge**
Added a `lsb_release -c` to [Installation](https://github.com/akerge/trivy#debianubuntu).

### CODE REVIEW

**Comment by knqyf263** [comment]
Thanks.

**Comment by knqyf263** [comment]
@akerge Thank you for contributing to Trivy. I have not prepared the Contribution License Agreement (CLA), but finally prepared it.

I would like you to sign CLA if possible. I apologize the inconvenience I have caused.
https://portal.helloworks.com/link/wvhTF78a4A9hICrm

If you have any questions, please let me know. Thanks again for your kind cooperation.

**Comment by knqyf263** [comment]
@akerge How about the above? I'm so sorry, but I need to revert this PR if CLA is not signed.

**Comment by akerge** [comment]
Hi, Teppei!

Thanks for the reminder! My apologies for the late reply. It's done now.

**Comment by knqyf263** [comment]
@akerge No problem! I appreciate your cooperation.

**Pull request merged**
