### PR TITLE
Fix some typos in the README or improve phrasing

### PR DESCRIPTION
**Pull request by NicolasCARPi**
also add .circleci to .dockerignore

Please accept my modest contribution to this great project :)

### CODE REVIEW

**Comment by knqyf263** [comment]
Thanks a lot!!

**Comment by knqyf263** [comment]
@NicolasCARPi Thank you for contributing to Trivy. I have not prepared the Contribution License Agreement (CLA), but finally prepared it.

I would like you to sign CLA if possible. I apologize the inconvenience I have caused.
https://portal.helloworks.com/link/wvhTF78a4A9hICrm

If you have any questions, please let me know. Thanks again for your kind cooperation.

**Comment by NicolasCARPi** [comment]
@knqyf263 done!

I went through the same thing myself a few weeks back for [my project](https://github.com/elabftw/elabftw) ;)

I don't know if you can do that with helloworks, but for me there is a bot asking contributors to sign directly on the PR, so the PR is not green until the CLA is signed. I use cla-assistant.io.

**Comment by knqyf263** [comment]
@NicolasCARPi Thank you! 

Yes, I also think about introducing the CLA bot. I didn't know cla-assistant.io. Thanks.

**Pull request merged**
