### PR TITLE
Added alpine into dbnames

### PR DESCRIPTION
**Pull request by Code-Hex**
same as title

### CODE REVIEW

**Comment by tomoyamachi** [comment]
I think it's better to use `all` database const from updateMap keys.
It only has to change `updateMap` when additional another DB in the future.

**Comment by Code-Hex** [comment]
yeah, i think so. but if we get from `map`, it doesn't promise order. is that OK?

**Comment by knqyf263** [comment]
@Code-Hex It's OK!

**Comment by Code-Hex** [comment]
done!!

**Comment by knqyf263** [comment]
Thanks!

**Pull request merged**
